### ISSUE TITLE
Weapons have a long range problem

### ISSUE THREAD

**Issue by blastdarkness** [multinettt/ARC-9_BOCW#2]
I don't know if it's personal or part of the mod but the weapons does not do any damage at long range

Approximately the damage disappears from 6 or 5 meters

**Comment by multinettt** [comment]
It's probably personal since they just work for me. If you mean the shotgun that's fair because it's so unfinished.

**Comment by blastdarkness** [comment]
I already solved it, I just needed to activate the "physical bullets" option
